nameOverride: messages
fullnameOverride: messages

image:
  repository: chirper/messages
  tag: dev

service:
  ports:
    - name: http
      port: 80
      targetPort: 4009
      containerPort: 4009
    - name: grpc
      port: 50059
      targetPort: 50059
      containerPort: 50059

env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "4009"
  - name: GRPC_BIND_URL
    value: 0.0.0.0:50059
  - name: IDENTITY_GRPC_URL
    value: identity:50051
  - name: PROFILE_GRPC_URL
    value: profile:50052
  - name: GRAPH_GRPC_URL
    value: graph:50054

envFromSecrets:
  - chirper-database
